routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */


Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath']
    ],
    function () {
        /** ADD ALL LOCALIZED ROUTES INSIDE THIS GROUP **/
        Route::get('/', function () {
            return view('auth.login');
        });
        Auth::routes(['register' => false]);
        Route::group(['middleware' => 'auth'], function () {
            Route::get('/dashboard', 'Dashboard\DashboardController@index')->name(
                'dashboard'
            );
            Route::resource('/moderator', 'Dashboard\ModeratorController')->except([
                'show'
            ]);
            Route::get('/moderator/profile', 'Dashboard\ModeratorController@profile')->name(
                'moderator.profile'
            );
            Route::resource('/category', 'Dashboard\CategoryController')->except([
                'show'
            ]);
            Route::resource('/product', 'Dashboard\ProductController')->except([
                'show'
            ]);
            Route::get('/searchsale', ['uses' => 'Dashboard\ProductController@searchsale', 'as' => 'product.searchsale']);
            Route::get('/searchpurchase', ['uses' => 'Dashboard\ProductController@searchpurchase', 'as' => 'product.searchpurchase']);
            Route::get('/addproduct', ['uses' => 'Dashboard\ProductController@addproduct', 'as' => 'product.addproduct']);
            Route::get('/barcode', 'Dashboard\ProductController@barcode');
            Route::put('/updateprice/{id}', 'Dashboard\ProductController@updateprice');

            Route::put('/paymentdue/{id}', 'Dashboard\SaleController@paymentdue');
            Route::put('/paymentduep/{id}', 'Dashboard\purchaseController@paymentduep');
            Route::resource('/sale', 'Dashboard\SaleController');
            Route::resource('/purchase', 'Dashboard\PurchaseController');
            Route::resource('/client', 'Dashboard\ClientController')->except([
                'show'
            ]);
            Route::get('/client/detail/{id}', 'Dashboard\ClientController@saledetail')->name('client.detail');
            Route::resource('/provider', 'Dashboard\ProviderController')->except([
                'show'
            ]);
            Route::get('/provider/detail/{id}', 'Dashboard\ProviderController@purchasedetail')->name('provider.detail');

            // spending route

            Route::post('/newspend', 'Dashboard\SpendingController@store');
            Route::put('/updatespend/{id}', 'Dashboard\SpendingController@updatespend');
            Route::resource('/spending', 'Dashboard\SpendingController')->except([
                'show'
            ]);

            // Money box route
            Route::get('/moneybox', 'Dashboard\MoneyBoxController@index')->name('moneybox');
            Route::post('/moneybox-filter', 'Dashboard\MoneyBoxController@filterSale')->name('moneyboxfilter');

            // generale Settings route
            Route::resource('/generalsetting', 'Dashboard\GeneralSettingController')->except([
                'show', 'update', 'destroy', 'create', 'edit'
            ]);
        });
    }
);

app/Http/Controllers/Dashboard/CategoryController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $categories = Category::all();
        return view('dashboard.category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'category_name' => 'required|unique:categories,category_name',

        ]);
        Category::create($request->all());
        toast('Category created Successfully', 'success', 'top-right');
        return redirect()->route('category.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('dashboard.category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $request->validate([
            'category_name' => 'required|unique:categories,category_name,' . $category->id,

        ]);
        $category->update($request->all());
        toast('Category Updated Successfully', 'success', 'top-right');
        return redirect()->route('category.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();
        toast('Category deleted Successfully', 'error', 'top-right');
        return redirect()->route('category.index');
    }
}

app/Http/Controllers/Dashboard/ClientController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Sale;
use App\Client;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //$allclients = Client::all();
        $clients = Client::all();
        // $sales = Sale::all();
        // foreach ($allclients as $key => $value) {
        //     dd($value->sales->sum('due'));
        // }

        return view('dashboard.client.index', compact('clients'));
    }


    public function saledetail($id)
    {
        //$allclients = Client::all();
        $client = Client::find($id);
        // $sales = Sale::all();
        // foreach ($allclients as $key => $value) {
        //     dd($value->sales->sum('due'));
        // }
        //dd($client->sales);


        return view('dashboard.client.saledetail', compact('client'));
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.client.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'client_name' => 'required',
            'phone' => 'required',
            'address' => 'required',

        ]);
        Client::create($request->all());
        toast('Client created Successfully', 'success', 'top-right');
        if (!$request->ajax()) {
            return redirect()->route('client.index');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function show(Client $client)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function edit(Client $client)
    {
        return view('dashboard.client.edit', compact('client'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Client $client)
    {
        $request->validate([
            'client_name' => 'required',
            'phone' => 'required',
            'address' => 'required',

        ]);
        $client->update($request->all());
        toast('Client Updated Successfully', 'success', 'top-right');
        return redirect()->route('client.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function destroy(Client $client)
    {
        $client->delete();
        toast('Client deleted Successfully', 'error', 'top-right');
        return redirect()->route('client.index');
    }
}

app/Http/Controllers/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Sale;
use App\User;
use App\Product;
use App\Category;
use App\Purchase;
use App\GeneralSetting;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;
use App\MoneyBox;
use App\Spending;
use RealRashid\SweetAlert\Facades\Alert;

class DashboardController extends Controller
{
    public function index()
    {
        $moderator = User::all();
        $categories = Category::all();
        $products = Product::all();
        //$sumprofit = collect($products)->sum('purchase_price', '-', 'sale_price');
        $sales = Sale::all();
        $purchases = Purchase::all();
        $spendmoneys = Spending::all();
        $totalspendmoneys = collect($spendmoneys)->sum('spending_price');
        //$moneybox = MoneyBox::all();
        $today = Carbon::today();
        // Count number of Sale today
        $sales_today = Sale::whereDate('created_at', '=', $today);
        //sum of due of Sale today
        $sale_due_today = Sale::whereDate('created_at', '=', $today)->sum('due');
        //sum of spending in day
        $spending_today = Spending::whereDate('created_at', '=', $today)->sum('spending_price');


        // Count number of Purchase today
        $purchases_today = Purchase::whereDate('created_at', '=', $today);
        //dd($sales_today);
        // foreach ($salesproducts as $key => $salesproduct) {
        //     $product_sales = $salesproduct->products;
        //     $sp_quantity = $salesproduct->pivot->quantity;
        //     dd($sp_quantity);
        // }
        // Best product that sale
        $topsales = DB::table('product_sale')
            ->leftJoin('products', 'products.id', '=', 'product_sale.product_id')
            ->select(
                'products.id',
                'products.product_name',
                'product_sale.product_id',
                DB::raw('SUM(product_sale.quantity) as total')
            )
            ->groupBy('products.id', 'product_sale.product_id', 'products.product_name')
            ->orderBy('total', 'desc')
            ->limit(6)
            ->get();

        // Best product that purchase
        $toppurchases = DB::table('product_purchase')
            ->leftJoin('products', 'products.id', '=', 'product_purchase.product_id')
            ->select(
                'products.id',
                'products.product_name',
                'product_purchase.product_id',
                DB::raw('SUM(product_purchase.quantity) as total')
            )
            ->groupBy('products.id', 'product_purchase.product_id', 'products.product_name')
            ->orderBy('total', 'desc')
            ->limit(6)
            ->get();
        //dd($salesproducts);


        $sale_profit = DB::table('product_sale')
            ->leftJoin('products', 'products.id', '=', 'product_sale.product_id')
            ->leftJoin('sales', 'sales.id', '=', 'product_sale.sale_id')
            ->select(
                'sales.id',
                'products.product_name',
                'products.sale_price',
                'products.purchase_price',
                'product_sale.product_id',
                'product_sale.quantity as qty',
                'sales.created_at',
                //DB::raw('SUM(products.sale_price - products.purchase_price) as profit'),
                DB::raw('SUM(products.sale_price - products.purchase_price) * product_sale.quantity as profits'),
                DB::raw('DATE(sales.created_at) as date')

            )
            ->groupBy('sales.id', 'product_sale.product_id', 'products.product_name', 'sales.created_at', 'date', 'qty')
            ->orderBy('date')
            ->whereDate('sales.created_at', '=', $today)
            ->get();
        //dd($sale_profit);

        $sumprofit = $sale_profit->sum('profits') - $sale_due_today - $spending_today;
        //dd($sumprofit);

        //dd($sumprofit);
        // Product with min stock
        $stock_alerts = DB::table('products')->where('stock', '<=', 'min_stock')->paginate(3, ['*'], 'stockalert');

        //dd($stock_alerts);
        return view(
            'dashboard.index',
            compact(
                'moderator',
                'categories',
                'products',
                'sumprofit',
                'topsales',
                'toppurchases',
                'stock_alerts',
                'sales',
                'sales_today',
                'purchases',
                'purchases_today',
                'totalspendmoneys'
            )
        );
    }
    public function pos()
    {
        $moderator = User::all();
        $categories = Category::all();
        $products = Product::all();
        return view('dashboard.pos.index', compact('moderator', 'categories', 'products'));
    }
}

app/Http/Controllers/Dashboard/GeneralSettingController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Product;
use App\GeneralSetting;
use Milon\Barcode\DNS1D;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\ImageManagerStatic as Image;

class GeneralSettingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(GeneralSetting $generalSetting)
    {
        $products = Product::all();

        return view('dashboard.settings.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'store_name' => 'required',
            'activity' =>'required',
            'phone'=>'required',
            'address' => 'required',
            'start_day' => 'required',
            'image' => 'image',
            'investment_capital' => 'required',
        ]);
        $id = $request->input('id');
        $general_setting = GeneralSetting::findOrFail($id);
        $request_data = $request->all();
        if ($request->image) {
            if ($general_setting->image != 'logo_default.png') {
                Storage::disk('public_uploads')->delete(
                    '/settings/' . $general_setting->image
                );
            }
            Image::make($request->image)
                ->resize(160, 160, function ($constraint) {
                    $constraint->aspectRatio();
                })
                ->save(
                    public_path(
                        'uploads/settings/' . $request->image->hashName()
                    )
                );
            $request_data['image'] = $request->image->hashName();
        }
        $general_setting->update($request_data);
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\GeneralSetting  $generalSetting
     * @return \Illuminate\Http\Response
     */
    public function show(GeneralSetting $generalSetting)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\GeneralSetting  $generalSetting
     * @return \Illuminate\Http\Response
     */
    public function edit(GeneralSetting $generalSetting)
    {
        //


    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\GeneralSetting  $generalSetting
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, GeneralSetting $generalSetting)
    {
        //
    }

    public function updatesetting(Request $request)
    { }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\GeneralSetting  $generalSetting
     * @return \Illuminate\Http\Response
     */
    public function destroy(GeneralSetting $generalSetting)
    {
        //
    }
}

resources/views/dashboard/moderator/create.blade.php
@extends('layouts.main')


@section('content')

<div class="col-md-12">
    <div class="card card-primary">
        <div class="card-header with-border">
            <h3 class="card-title">@lang('site.createmoderator')</h3>
        </div>

        <!-- /.card-header -->
        <div class="card-body">

            <form action="{{ route('moderator.store') }}" method="post" enctype="multipart/form-data">
                {{ csrf_field() }}
                {{ method_field('post') }}
                @include('partials._errors')
                <div class="row">

                    <div class="col-md-6">
                        <div class="form-group">
                            <label>@lang('site.firstname')</label>
                            <input type="text" name="first_name" id="" class="form-control"
                                value="{{ old('first_name') }}" required>
                        </div>
                        <div class="form-group">
                            <label>@lang('site.lastname')</label>
                            <input type="text" name="last_name" id="" class="form-control"
                                value="{{ old('last_name') }}" required>
                        </div>
                        <div class="form-group">
                            <label>@lang('site.email')</label>
                            <input type="email" name="email" id="" class="form-control" value="{{ old('email') }}"
                                required>
                        </div>
                        <div class="form-group">
                            <label>@lang('site.password')</label>
                            <input type="password" name="password" id="" class="form-control" required>
                        </div>
                        <div class="form-group">
                            <label>@lang('site.passwordconfirmation')</label>
                            <input type="password" name="password_confirmation" id="" class="form-control" required>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <label for="">@lang('site.photo')</label>
                        <div class="form-group">
                            <div class="custom-file">
                                <input type="file" name="image" class="form-control image custom-file-input"
                                    id="customFile">
                                <label class="custom-file-label" for="customFile">@lang('site.choosephoto')</label>
                            </div>
                        </div>
                        <div class="form-group">
                            <img src="{{ asset('uploads/moderator_images/default.png') }}" style="width:200px;"
                                class="img-circle img-thumbnail img-preview" alt="" srcset="">
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <div class="card">
                                <div class="card-header d-flex p-0">
                                    <h3 class="card-title p-3">@lang('site.moderatorpermission')</h3>
                                    @php
                                    $models =
                                    ['users','categories','products','clients','providers','sales','purchases','spendings','moneybox','generalsetting'];
                                    $maps = ['create', 'read', 'update', 'delete'];
                                    @endphp
                                    <ul class="nav nav-pills ml-auto p-2">
                                        @foreach ($models as $index=>$model)
                                        <li class="nav-item {{ $index == 0 ? 'active' :'' }}"><a
                                                class="nav-link {{ $index == 0 ? 'active' :'' }}" href="#{{ $model }}"
                                                data-toggle="tab">{{ $model }}</a></li>
                                        @endforeach
                                    </ul>
                                </div><!-- /.card-header -->
                                <div class="card-body">
                                    <div class="tab-content">
                                        <!-- /.tab-pane -->
                                        @foreach ($models as $index=>$model)
                                        <div class="tab-pane  {{ $index == 0 ? 'active' :'' }}" id="{{ $model }}">
                                            @foreach ($maps as $map)
                                            <label><input type="checkbox" name="permissions[]"
                                                    value="{{ $map .'_'. $model }}">
                                                {{
                                                $map }}</label>
                                            @endforeach
                                        </div>
                                        @endforeach

                                    </div>
                                    <!-- /.tab-content -->
                                </div><!-- /.card-body -->
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer form-group">
                    <button type="submit" class="btn btn-success" href="{{ route('moderator.store') }}"><i
                            class="fas fa-user-plus"></i>
                        @lang('site.createmoderator')</button>
                </div>
            </form>

        </div>
        <!-- /.card-body -->

    </div>
</div>


@stop

resources/views/dashboard/moderator/index.blade.php
@extends('layouts.main')


@section('content')
@include('sweet::alert')
<div class="col-md-12">
    <div class="card card-primary">
        <div class="card-header with-border">

            <form action="{{ route('product.index') }}" method="get">

                <div class="row no-gutters">
                    <div class="col-12 col-sm-6 col-md-8">
                        <h3 class="card-title">@lang('site.moderators')</h3>
                    </div>
                    <div class="col-6 col-md-4">
                        @if (auth()->user()->hasPermission('create_users'))
                        <a type="" class="btn btn-success btn float-right" style="" href="{{ route('moderator.create') }}"><i
                                class="fas fa-user-plus"></i>
                            @lang('site.createmoderator')</a>
                        @else
                        <a type="" class="btn btn-success disabled btn float-right" href="#"><i class="fas fa-user-plus"></i>
                            @lang('site.createmoderator')</a>
                        @endif
                    </div>
                </div>
            </form>
        </div>

        <!-- /.card-header -->
        <div class="card-body">
            <div id="category_table_wrapper" class="dataTables_wrapper dt-bootstrap4">
                <div class="row">
                    <div class="col-sm-12">
                        <table id="category_table" class="table table-bordered table-striped table-hover  dataTable"
                            role="grid" aria-describedby="category_table_info">
                            <thead>
                                <tr role="row">
                                    <th class="sorting_asc" tabindex="0" aria-controls="category_table" rowspan="1"
                                        colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending"
                                        style="width: 283px;">No</th>
                                    <th class="sorting" tabindex="0" aria-controls="category_table" rowspan="1" colspan="1"
                                        aria-label="Browser: activate to sort column ascending" style="width: 359px;">@lang('site.firstname')</th>
                                    <th class="sorting" tabindex="0" aria-controls="category_table" rowspan="1" colspan="1"
                                        aria-label="Platform(s): activate to sort column ascending" style="width: 320px;">@lang('site.lastname')</th>
                                    <th class="sorting" tabindex="0" aria-controls="category_table" rowspan="1" colspan="1"
                                        aria-label="Platform(s): activate to sort column ascending" style="width: 320px;">@lang('site.email')</th>
                                    <th class="sorting" tabindex="0" aria-controls="category_table" rowspan="1" colspan="1"
                                        aria-label="Platform(s): activate to sort column ascending" style="width: 320px;">@lang('site.photo')</th>
                                    <th class="sorting" tabindex="0" aria-controls="category_table" rowspan="1" colspan="1"
                                        aria-label="Engine version: activate to sort column ascending" style="width: 243px;">@lang('site.action')</th>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach ($moderator as $index => $moderators)
                                <tr>
                                    <td>{{ $index + 1 }}</td>
                                    <td>{{ $moderators -> first_name }}</td>
                                    <td>{{ $moderators -> last_name }}</td>
                                    <td>{{ $moderators -> email }}</td>
                                    <td><img src="{{ $moderators -> image_path }}" style="width:50px;" class="img-circle img-thumbnail"
                                            alt="" srcset=""></td>
                                    <td>
                                        @if (auth()->user()->hasPermission('update_users'))
                                        <a class="btn btn-warning btn-sm" href="{{ route('moderator.edit', $moderators->id) }}"><i
                                                class="fas fa-user-edit"></i>
                                            @lang('site.edit')</a>
                                        @else
                                        <a class="btn btn-warning btn-sm disabled" href="{{ route('moderator.edit', $moderators->id) }}"><i
                                                class="fas fa-user-edit"></i>
                                            @lang('site.edit')</a>
                                        @endif
                                        @if (auth()->user()->hasPermission('delete_users'))
                                        <button id="delete" onclick="deletemoderator({{ $moderators->id }})" class="btn btn-danger btn-sm"><i
                                                class="fas fa-user-times"></i>
                                            @lang('site.delete')</button>
                                        <form id="form-delete-{{ $moderators->id }}" action="{{ route('moderator.destroy', $moderators->id) }}"
                                            method="post" style="display:inline-block;">
                                            {{ csrf_field() }}
                                            {{ method_field('delete') }}
                                        </form>
                                        @else
                                        <button type="submit" class="btn btn-danger btn-sm disabled"><i class="fas fa-user-times"></i>
                                            @lang('site.delete')</button>
                                        @endif

                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th rowspan="1" colspan="1">No</th>
                                    <th rowspan="1" colspan="1">@lang('site.firstname')</th>
                                    <th rowspan="1" colspan="1">@lang('site.lastname')</th>
                                    <th rowspan="1" colspan="1">@lang('site.email')</th>
                                    <th rowspan="1" colspan="1">@lang('site.photo')</th>
                                    <th rowspan="1" colspan="1">@lang('site.action')</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.card-body -->


    </div>
</div>


@stop