routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */


Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath']
    ],
    function () {
        /** ADD ALL LOCALIZED ROUTES INSIDE THIS GROUP **/
        Route::get('/', function () {
            return view('auth.login');
        });
        Auth::routes(['register' => false]);
        Route::group(['middleware' => 'auth'], function () {
            Route::get('/dashboard', 'Dashboard\DashboardController@index')->name(
                'dashboard'
            );
            Route::resource('/moderator', 'Dashboard\ModeratorController')->except([
                'show'
            ]);
            Route::get('/moderator/profile', 'Dashboard\ModeratorController@profile')->name(
                'moderator.profile'
            );
            Route::resource('/category', 'Dashboard\CategoryController')->except([
                'show'
            ]);
            Route::resource('/product', 'Dashboard\ProductController')->except([
                'show'
            ]);
            Route::get('/searchsale', ['uses' => 'Dashboard\ProductController@searchsale', 'as' => 'product.searchsale']);
            Route::get('/searchpurchase', ['uses' => 'Dashboard\ProductController@searchpurchase', 'as' => 'product.searchpurchase']);
            Route::get('/addproduct', ['uses' => 'Dashboard\ProductController@addproduct', 'as' => 'product.addproduct']);
            Route::get('/barcode', 'Dashboard\ProductController@barcode');
            Route::put('/updateprice/{id}', 'Dashboard\ProductController@updateprice');

            Route::put('/paymentdue/{id}', 'Dashboard\SaleController@paymentdue');
            Route::put('/paymentduep/{id}', 'Dashboard\purchaseController@paymentduep');
            Route::resource('/sale', 'Dashboard\SaleController');
            Route::resource('/purchase', 'Dashboard\PurchaseController');
            Route::resource('/client', 'Dashboard\ClientController')->except([
                'show'
            ]);
            Route::get('/client/detail/{id}', 'Dashboard\ClientController@saledetail')->name('client.detail');
            Route::resource('/provider', 'Dashboard\ProviderController')->except([
                'show'
            ]);
            Route::get('/provider/detail/{id}', 'Dashboard\ProviderController@purchasedetail')->name('provider.detail');

            // spending route

            Route::post('/newspend', 'Dashboard\SpendingController@store');
            Route::put('/updatespend/{id}', 'Dashboard\SpendingController@updatespend');
            Route::resource('/spending', 'Dashboard\SpendingController')->except([
                'show'
            ]);

            // Money box route
            Route::get('/moneybox', 'Dashboard\MoneyBoxController@index')->name('moneybox');
            Route::post('/moneybox-filter', 'Dashboard\MoneyBoxController@filterSale')->name('moneyboxfilter');

            // generale Settings route
            Route::resource('/generalsetting', 'Dashboard\GeneralSettingController')->except([
                'show', 'update', 'destroy', 'create', 'edit'
            ]);
        });
    }
);

app/Http/Controllers/Dashboard/CategoryController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $categories = Category::all();
        return view('dashboard.category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'category_name' => 'required|unique:categories,category_name',

        ]);
        Category::create($request->all());
        toast('Category created Successfully', 'success', 'top-right');
        return redirect()->route('category.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('dashboard.category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $request->validate([
            'category_name' => 'required|unique:categories,category_name,' . $category->id,

        ]);
        $category->update($request->all());
        toast('Category Updated Successfully', 'success', 'top-right');
        return redirect()->route('category.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();
        toast('Category deleted Successfully', 'error', 'top-right');
        return redirect()->route('category.index');
    }
}

app/Http/Controllers/Dashboard/ClientController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Sale;
use App\Client;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //$allclients = Client::all();
        $clients = Client::all();
        // $sales = Sale::all();
        // foreach ($allclients as $key => $value) {
        //     dd($value->sales->sum('due'));
        // }

        return view('dashboard.client.index', compact('clients'));
    }


    public function saledetail($id)
    {
        //$allclients = Client::all();
        $client = Client::find($id);
        // $sales = Sale::all();
        // foreach ($allclients as $key => $value) {
        //     dd($value->sales->sum('due'));
        // }
        //dd($client->sales);


        return view('dashboard.client.saledetail', compact('client'));
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.client.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'client_name' => 'required',
            'phone' => 'required',
            'address' => 'required',

        ]);
        Client::create($request->all());
        toast('Client created Successfully', 'success', 'top-right');
        if (!$request->ajax()) {
            return redirect()->route('client.index');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function show(Client $client)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function edit(Client $client)
    {
        return view('dashboard.client.edit', compact('client'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Client $client)
    {
        $request->validate([
            'client_name' => 'required',
            'phone' => 'required',
            'address' => 'required',

        ]);
        $client->update($request->all());
        toast('Client Updated Successfully', 'success', 'top-right');
        return redirect()->route('client.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function destroy(Client $client)
    {
        $client->delete();
        toast('Client deleted Successfully', 'error', 'top-right');
        return redirect()->route('client.index');
    }
}

app/Http/Controllers/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Sale;
use App\User;
use App\Product;
use App\Category;
use App\Purchase;
use App\GeneralSetting;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;
use App\MoneyBox;
use App\Spending;
use RealRashid\SweetAlert\Facades\Alert;

class DashboardController extends Controller
{
    public function index()
    {
        $moderator = User::all();
        $categories = Category::all();
        $products = Product::all();
        //$sumprofit = collect($products)->sum('purchase_price', '-', 'sale_price');
        $sales = Sale::all();
        $purchases = Purchase::all();
        $spendmoneys = Spending::all();
        $totalspendmoneys = collect($spendmoneys)->sum('spending_price');
        //$moneybox = MoneyBox::all();
        $today = Carbon::today();
        // Count number of Sale today
        $sales_today = Sale::whereDate('created_at', '=', $today);
        //sum of due of Sale today
        $sale_due_today = Sale::whereDate('created_at', '=', $today)->sum('due');
        //sum of spending in day
        $spending_today = Spending::whereDate('created_at', '=', $today)->sum('spending_price');


        // Count number of Purchase today
        $purchases_today = Purchase::whereDate('created_at', '=', $today);
        //dd($sales_today);
        // foreach ($salesproducts as $key => $salesproduct) {
        //     $product_sales = $salesproduct->products;
        //     $sp_quantity = $salesproduct->pivot->quantity;
        //     dd($sp_quantity);
        // }
        // Best product that sale
        $topsales = DB::table('product_sale')
            ->leftJoin('products', 'products.id', '=', 'product_sale.product_id')
            ->select(
                'products.id',
                'products.product_name',
                'product_sale.product_id',
                DB::raw('SUM(product_sale.quantity) as total')
            )
            ->groupBy('products.id', 'product_sale.product_id', 'products.product_name')
            ->orderBy('total', 'desc')
            ->limit(6)
            ->get();

        // Best product that purchase
        $toppurchases = DB::table('product_purchase')
            ->leftJoin('products', 'products.id', '=', 'product_purchase.product_id')
            ->select(
                'products.id',
                'products.product_name',
                'product_purchase.product_id',
                DB::raw('SUM(product_purchase.quantity) as total')
            )
            ->groupBy('products.id', 'product_purchase.product_id', 'products.product_name')
            ->orderBy('total', 'desc')
            ->limit(6)
            ->get();
        //dd($salesproducts);


        $sale_profit = DB::table('product_sale')
            ->leftJoin('products', 'products.id', '=', 'product_sale.product_id')
            ->leftJoin('sales', 'sales.id', '=', 'product_sale.sale_id')
            ->select(
                'sales.id',
                'products.product_name',
                'products.sale_price',
                'products.purchase_price',
                'product_sale.product_id',
                'product_sale.quantity as qty',
                'sales.created_at',
                //DB::raw('SUM(products.sale_price - products.purchase_price) as profit'),
                DB::raw('SUM(products.sale_price - products.purchase_price) * product_sale.quantity as profits'),
                DB::raw('DATE(sales.created_at) as date')

            )
            ->groupBy('sales.id', 'product_sale.product_id', 'products.product_name', 'sales.created_at', 'date', 'qty')
            ->orderBy('date')
            ->whereDate('sales.created_at', '=', $today)
            ->get();
        //dd($sale_profit);

        $sumprofit = $sale_profit->sum('profits') - $sale_due_today - $spending_today;
        //dd($sumprofit);

        //dd($sumprofit);
        // Product with min stock
        $stock_alerts = DB::table('products')->where('stock', '<=', 'min_stock')->paginate(3, ['*'], 'stockalert');

        //dd($stock_alerts);
        return view(
            'dashboard.index',
            compact(
                'moderator',
                'categories',
                'products',
                'sumprofit',
                'topsales',
                'toppurchases',
                'stock_alerts',
                'sales',
                'sales_today',
                'purchases',
                'purchases_today',
                'totalspendmoneys'
            )
        );
    }
    public function pos()
    {
        $moderator = User::all();
        $categories = Category::all();
        $products = Product::all();
        return view('dashboard.pos.index', compact('moderator', 'categories', 'products'));
    }
}

app/Http/Controllers/Dashboard/GeneralSettingController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Product;
use App\GeneralSetting;
use Milon\Barcode\DNS1D;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\ImageManagerStatic as Image;

class GeneralSettingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(GeneralSetting $generalSetting)
    {
        $products = Product::all();

        return view('dashboard.settings.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'store_name' => 'required',
            'activity' =>'required',
            'phone'=>'required',
            'address' => 'required',
            'start_day' => 'required',
            'image' => 'image',
            'investment_capital' => 'required',
        ]);
        $id = $request->input('id');
        $general_setting = GeneralSetting::findOrFail($id);
        $request_data = $request->all();
        if ($request->image) {
            if ($general_setting->image != 'logo_default.png') {
                Storage::disk('public_uploads')->delete(
                    '/settings/' . $general_setting->image
                );
            }
            Image::make($request->image)
                ->resize(160, 160, function ($constraint) {
                    $constraint->aspectRatio();
                })
                ->save(
                    public_path(
                        'uploads/settings/' . $request->image->hashName()
                    )
                );
            $request_data['image'] = $request->image->hashName();
        }
        $general_setting->update($request_data);
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\GeneralSetting  $generalSetting
     * @return \Illuminate\Http\Response
     */
    public function show(GeneralSetting $generalSetting)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\GeneralSetting  $generalSetting
     * @return \Illuminate\Http\Response
     */
    public function edit(GeneralSetting $generalSetting)
    {
        //


    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\GeneralSetting  $generalSetting
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, GeneralSetting $generalSetting)
    {
        //
    }

    public function updatesetting(Request $request)
    { }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\GeneralSetting  $generalSetting
     * @return \Illuminate\Http\Response
     */
    public function destroy(GeneralSetting $generalSetting)
    {
        //
    }
}

resources/views/dashboard/client/create.blade.php
@extends('layouts.main')


@section('content')

<div class="col-md-12">
    <div class="card card-primary">
        <div class="card-header with-border">
            <h3 class="card-title">@lang('site.createclient')</h3>
        </div>

        <!-- /.card-header -->
        <div class="card-body">

            <form action="{{ route('client.store') }}" method="post">
                {{ csrf_field() }}
                {{ method_field('post') }}
                @include('partials._errors')
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>@lang('site.clientname')</label>
                            <input type="text" name="client_name" id="" class="form-control"
                                value="{{ old('client_name') }}">
                        </div>
                        <div class="form-group">
                            <label>@lang('site.phone')</label>
                            <input type="text" name="phone" id="" class="form-control" value="{{ old('phone') }}">
                        </div>
                        <div class="form-group">
                            <label>@lang('site.address')</label>
                            <textarea type="text" name="address" id=""
                                class="form-control">{{ old('address') }}</textarea>
                        </div>
                        <div class="form-group">
                            <label>@lang('site.description')</label>
                            <textarea type="text" name="description" id=""
                                class="form-control">{{ old('description') }}</textarea>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>@lang('site.numeroregistrecommerce')</label>
                            <input type="text" name="rc" id="" class="form-control" value="{{ old('rc') }}">
                        </div>
                        <div class="form-group">
                            <label>@lang('site.numeroarticle')</label>
                            <input type="number" name="article" id="" class="form-control" value="{{ old('article') }}">
                        </div>
                        <div class="form-group">
                            <label>@lang('site.nif')</label>
                            <input type="number" name="nif" id="" class="form-control" value="{{ old('nif') }}">
                        </div>
                        <div class="form-group">
                            <label>@lang('site.nis')</label>
                            <input type="number" name="nis" id="" class="form-control" value="{{ old('nis') }}">
                        </div>
                    </div>
                </div>
                <div class="modal-footer form-group">
                    <button type="submit" class="btn btn-success" href="{{ route('client.store') }}"><i
                            class="fas fa-user-plus"></i> @lang('site.createclient')</button>
                </div>
            </form>

        </div>
        <!-- /.card-body -->

    </div>
</div>


@stop

resources/views/dashboard/client/edit.blade.php
@extends('layouts.main')


@section('content')

<div class="col-md-12">
    <div class="card card-primary">
        <div class="card-header with-border">
            <h3 class="card-title">@lang('site.editclient')</h3>
        </div>

        <!-- /.card-header -->
        <div class="card-body">

            <form action="{{ route('client.update', $client->id) }}" method="post">
                {{ csrf_field() }}
                {{ method_field('put') }}
                @include('partials._errors')
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>@lang('site.clientname')</label>
                            <input type="text" name="client_name" id="" class="form-control"
                                value="{{ $client->client_name }}">
                        </div>
                        <div class="form-group">
                            <label>@lang('site.phone')</label>
                            <input type="text" name="phone" id="" class="form-control" value="{{ $client->phone }}">
                        </div>
                        <div class="form-group">
                            <label>@lang('site.address')</label>
                            <textarea type="text" name="address" id=""
                                class="form-control">{{ $client->address }}</textarea>
                        </div>
                        <div class="form-group">
                            <label>@lang('site.description')</label>
                            <textarea type="text" name="description" id=""
                                class="form-control">{{ $client->description }}</textarea>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>@lang('site.numeroregistrecommerce')</label>
                            <input type="text" name="rc" id="" class="form-control" value="{{ $client->rc }}">
                        </div>
                        <div class="form-group">
                            <label>@lang('site.numeroarticle')</label>
                            <input type="number" name="article" id="" class="form-control"
                                value="{{ $client->article }}">
                        </div>
                        <div class="form-group">
                            <label>@lang('site.nif')</label>
                            <input type="number" name="nif" id="" class="form-control" value="{{ $client->nif }}">
                        </div>
                        <div class="form-group">
                            <label>@lang('site.nis')</label>
                            <input type="number" name="nis" id="" class="form-control" value="{{ $client->nis }}">
                        </div>
                    </div>
                </div>
                <div class="modal-footer form-group">
                    <button type="submit" class="btn btn-primary"><i class="fas fa-edit"></i>
                        @lang('site.updateclient')</button>
                </div>
            </form>

        </div>
        <!-- /.card-body -->

    </div>
</div>


@stop

resources/views/dashboard/client/saledetail.blade.php
@extends('layouts.main')


@section('content')

<div class="col-md-12">
    <div class="card card-primary">
        <div class="card-header with-border">
            <div class="row no-gutters">
                <div class="col-12 col-sm-6 col-md-8">
                    <h3 class="card-title">@lang('site.clientsalesdetails')</h3>
                </div>
            </div>
        </div>

        <!-- /.card-header -->
        <div class="card-body">
            <div id="category_table_wrapper" class="dataTables_wrapper dt-bootstrap4">
                <div class="row">
                    <div class="col-sm-12">
                        <table id="category_table" class="table table-bordered table-striped table-hover  dataTable"
                            role="grid" aria-describedby="category_table_info">
                            <thead>
                                <tr role="row">
                                    <th class="sorting_asc" tabindex="0" aria-controls="category_table" rowspan="1"
                                        colspan="1" aria-sort="ascending"
                                        aria-label="Rendering engine: activate to sort column descending"
                                        style="width: 283px;">No</th>
                                    <th class="sorting" tabindex="0" aria-controls="category_table" rowspan="1"
                                        colspan="1" aria-label="Browser: activate to sort column ascending"
                                        style="width: 359px;">@lang('site.numbersale')</th>
                                    <th class="sorting" tabindex="0" aria-controls="category_table" rowspan="1"
                                        colspan="1" aria-label="Platform(s): activate to sort column ascending"
                                        style="width: 320px;">@lang('site.total')</th>
                                    <th class="sorting" tabindex="0" aria-controls="category_table" rowspan="1"
                                        colspan="1" aria-label="Platform(s): activate to sort column ascending"
                                        style="width: 320px;">@lang('site.discount')</th>
                                    <th class="sorting" tabindex="0" aria-controls="category_table" rowspan="1"
                                        colspan="1" aria-label="Platform(s): activate to sort column ascending"
                                        style="width: 320px;">@lang('site.totalamount')</th>
                                    <th class="sorting" tabindex="0" aria-controls="category_table" rowspan="1"
                                        colspan="1" aria-label="Platform(s): activate to sort column ascending"
                                        style="width: 320px;">@lang('site.paid')</th>
                                    <th class="sorting" tabindex="0" aria-controls="category_table" rowspan="1"
                                        colspan="1" aria-label="Platform(s): activate to sort column ascending"
                                        style="width: 320px;">@lang('site.due')</th>
                                    <th class="sorting" tabindex="0" aria-controls="category_table" rowspan="1"
                                        colspan="1" aria-label="Engine version: activate to sort column ascending"
                                        style="width: 320px;">@lang('site.action')</th>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach ($client->sales as $index => $sale)

                                <tr>
                                    <td>{{ $index + 1 }}</td>
                                    <td>{{ $sale->number_sale }}</td>
                                    <td>{{ $sale->total }}</td>
                                    <td>{{ $sale->discount }}</td>
                                    @if ($sale->status == "paid")
                                    <td><span class="badge bg-success">{{ $sale->total_amount }}</span></td>
                                    @endif
                                    @if ($sale->status == "nopaid")
                                    <td><span class="badge bg-danger">{{ $sale->total_amount }}</span></td>
                                    @endif
                                    @if ($sale->status == "debt")
                                    <td><span class="badge bg-warning">{{ $sale->total_amount }}</span></td>
                                    @endif
                                    <td>{{ $sale->paid }}</td>
                                    <td>{{ $sale->due }}</td>
                                    <td>
                                        <a href="{{ route('sale.show', $sale->id) }}" class="btn btn-primary btn-sm"><i
                                                class="fas fa-print"></i></a>
                                    </td>

                                </tr>
                                @endforeach
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th rowspan="1" colspan="1">No</th>
                                    <th rowspan="1" colspan="1">@lang('site.numbersale')</th>
                                    <th rowspan="1" colspan="1">@lang('site.total')</th>
                                    <th rowspan="1" colspan="1">@lang('site.discount')</th>
                                    <th rowspan="1" colspan="1">@lang('site.totalamount')</th>
                                    <th rowspan="1" colspan="1">@lang('site.paid')</th>
                                    <th rowspan="1" colspan="1">@lang('site.due')</th>
                                    <th rowspan="1" colspan="1">@lang('site.action')</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection